<a href="https://colab.research.google.com/github/addieCodess/Gratiflow/blob/main/lecture3_prob_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv

--2025-06-06 04:40:59--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.169.117.172, 3.169.117.64, 3.169.117.127, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.169.117.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26440 (26K) [text/plain]
Saving to: ‘Sachin_ODI.csv’

Sachin_ODI.csv      100%[===================>]  25.82K  --.-KB/s    in 0s

2025-06-06 04:40:59 (66.5 MB/s) - ‘Sachin_ODI.csv’ saved [26440/26440]

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sachin_data  = pd.read_csv("Sachin_ODI.csv")

sachin_data = sachin_data.drop(columns=["Won","century"])

sachin_data .head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan

In [ ]:
sachin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   runs    360 non-null    int64
 1   NotOut  360 non-null    int64
 2   mins    360 non-null    object
 3   bf      360 non-null    int64
 4   fours   360 non-null    int64
 5   sixes   360 non-null    int64
 6   sr      360 non-null    float64
 7   Inns    360 non-null    int64
 8   Opp     360 non-null    object
 9   Ground  360 non-null    object
 10  Date    360 non-null    object
 11  Winner  360 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 33.9+ KB

# Find null values in each column

# Convert Date into Date type
- extract year and month

# calculate number of centuries scored by Sachin
- find % of centuries

# Visualize the distribution of
- runs
- strike rate

# Sachin's performance across different Innings

### Homework

In [ ]:
# H.W : Calculate outlier runs

# Find distribution of Sachin's matches against different teams

# Generate Correlation Matrix

# Is there a relationship between runs scored and strike rate?
- visualise the relationship

# Create columns for
- if match won by India (Boolean)
- if Sachin scored a century

# Identify matches where Sachin scored more than 50 runs as part of 4s and 6s

# Analyse Sachin's Performance over the years of his cricket career

In [ ]:
# define events
#event A: scored more than equal to 50
#event B: India won the match
#event_AB:

event_A = sachin_data[sachin_data['runs'] >= 50]
event_B = sachin_data[sachin_data['won_india']]

event_AB = sachin_data[(sachin_data['runs'] >= 50) & (sachin_data['won_india'])] # A intersection B

print(event_A.shape, event_B.shape)
print(event_AB.shape)

(121, 16) (184, 16)
(75, 16)

In [ ]:
# intersection
pd.merge(event_A, event_B, how='inner').shape

(75, 16)

In [ ]:
sachin_data.describe()

,runs,NotOut,bf,fours,sixes,sr,Inns,Date_new,match_year
count,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360,360.000000
mean,43.241667,0.083333,49.394444,4.858333,0.466667,75.295056,1.527778,2002-07-27 13:04:00,2002.102778
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,1995-02-16 00:00:00,1995.000000
25%,8.000000,0.000000,15.000000,1.000000,0.000000,57.030000,1.000000,1998-04-19 18:00:00,1998.000000
50%,30.000000,0.000000,35.000000,3.000000,0.000000,76.330000,2.000000,2001-10-25 00:00:00,2001.000000
75%,67.000000,0.000000,73.500000,8.000000,1.000000,97.822500,2.000000,2006-11-23 00:00:00,2006.000000
max,200.000000,1.000000,153.000000,25.000000,7.000000,196.550000,2.000000,2012-03-18 00:00:00,2012.000000
std,42.182452,0.276770,41.348576,4.722900,1.057669,34.980677,0.499923,NaN,4.764422

In [ ]:
sachin_data['NotOut'] = sachin_data['NotOut'].astype('str')
sachin_data.describe()

,runs,bf,fours,sixes,sr,Inns,Date_new,match_year
count,360.000000,360.000000,360.000000,360.000000,360.000000,360.000000,360,360.000000
mean,43.241667,49.394444,4.858333,0.466667,75.295056,1.527778,2002-07-27 13:04:00,2002.102778
min,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,1995-02-16 00:00:00,1995.000000
25%,8.000000,15.000000,1.000000,0.000000,57.030000,1.000000,1998-04-19 18:00:00,1998.000000
50%,30.000000,35.000000,3.000000,0.000000,76.330000,2.000000,2001-10-25 00:00:00,2001.000000
75%,67.000000,73.500000,8.000000,1.000000,97.822500,2.000000,2006-11-23 00:00:00,2006.000000
max,200.000000,153.000000,25.000000,7.000000,196.550000,2.000000,2012-03-18 00:00:00,2012.000000
std,42.182452,41.348576,4.722900,1.057669,34.980677,0.499923,NaN,4.764422